### ISSUE TITLE
Config example for lovelace button

### ISSUE THREAD

**Issue by jurgenhaas** [amaximus/anniversary#3]
Would you mind providing an example on how you configured the button component in Lovelace?

**Comment by amaximus** [comment]
Readme updated with custom button card example.

**Comment by jurgenhaas** [comment]
Oh great, that was quick 😃 - thanks a lot, I'll  give it a try tomorrow

**Comment by jurgenhaas** [comment]
Can confirm, the button card is working just fine.

The condition is confusing me a bit. Where is the binary sensor coming from? I don't have it and I wonder if that requires some extra steps to set this up?

**Comment by amaximus** [comment]
Since the conditional card accepts only state or state_not conditions while the anniversary sensor's state is a numerical value (number of days till the first upcoming event), the binary sensor just sets its state to on when the anniversary sensor's state value is less than 5 (days), so the custom button card will not be displayed all the time but only when the event is within 5 days.

**Comment by jurgenhaas** [comment]
Yes sure, but my problem is that the binary sensor named `binary_sensor.event_in_5d` doesn't exist in my HA instance. Should that be created by the plugin or do I have to create that myself?

**Comment by amaximus** [comment]
You should create the binary sensor if you want to use the conditional card (e.g. not display the custom button card all the time).
Mine looks like this:
```
platform: template
sensors:
  event_in_5d:
    value_template: >-
      {% if states('sensor.events') | float < 5 %}
        on
      {% else %}
        off
      {% endif %}
```

**Comment by jurgenhaas** [comment]
This is working great, thank you so much.
